# Generated by Django 6.0.1 on 2026-01-18 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='namn')),
            ],
            options={
                'verbose_name': 'checklista',
                'verbose_name_plural': 'checklistor',
            },
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='beskrivning')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.checklist')),
            ],
            options={
                'verbose_name': 'punkt',
                'verbose_name_plural': 'punkter',
            },
        ),
    ]
