#! /bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER sambo WITH PASSWORD '$DB_USER_PASSWORD';
	CREATE DATABASE sambo WITH OWNER sambo;
	GRANT ALL PRIVILEGES ON DATABASE sambo TO sambo;
EOSQL
