# Generated by Django 6.0.1 on 2026-02-21 18:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("content", models.BinaryField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "uppladdning",
                "verbose_name_plural": "uppladdningar",
            },
        ),
    ]
