# Generated by Django 6.0.1 on 2026-02-05 21:44

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models

import sambo.expense.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=50, verbose_name="namn")),
            ],
            options={
                "verbose_name": "nota",
                "verbose_name_plural": "notor",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=50, verbose_name="beskrivning")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7, verbose_name="summa")),
                ("spent_at", models.DateField(default=sambo.expense.models._today, verbose_name="spenderad")),
                (
                    "settled_at",
                    models.DateField(blank=True, default=datetime.date(9999, 12, 31), verbose_name="uppklarad"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="expense.bill"
                    ),
                ),
            ],
            options={
                "verbose_name": "utgift",
                "verbose_name_plural": "utgifter",
            },
        ),
    ]
