# Generated by Django 6.0.1 on 2026-02-08 14:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="settled_at",
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31), verbose_name="uppgjord"),
        ),
    ]
