# Generated by Django 6.0.1 on 2026-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_alter_expense_settled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="spent_by",
            field=models.CharField(blank=True, verbose_name="spenderad av"),
        ),
    ]
