# Generated by Django 6.0.1 on 2026-05-29 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0003_expense_spent_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="spent_by",
            new_name="paid_by",
        ),
    ]
