# Generated by Django 6.0.1 on 2026-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0004_rename_expense_spent_by_expense_paid_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="paid_by",
            field=models.CharField(blank=True, verbose_name="betalad av"),
        ),
    ]
