# Generated by Django 6.0.1 on 2026-01-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="mejladress")),
                ("is_active", models.BooleanField(verbose_name="är aktiv")),
                ("is_superuser", models.BooleanField(verbose_name="är superadmin")),
            ],
            options={
                "verbose_name": "användare",
                "verbose_name_plural": "användare",
            },
        ),
    ]
